import React from 'react';
import {
  Building2,
  CircleAlert,
  Gauge,
  Globe,
  Key,
  Lock,
  Mail,
  Mic,
  MicOff,
  MicVocal,
  Guitar,
  Piano,
  Drum,
  Music2,
  Music4,
  Phone,
  Search,
  SquarePlay,
  Type,
  Activity,
  AlarmClock,
  ArrowLeft,
  ArrowLeftRight,
  Bell,
  Bookmark,
  Calendar,
  Camera,
  ChartColumn,
  Check,
  CheckCheck,
  ChevronLeft,
  ChevronRight,
  CircleCheckBig,
  CircleHelp,
  CirclePlus,
  CircleX,
  Clock,
  CloudDownload,
  CloudOff,
  CloudUpload,
  EllipsisVertical,
  Eye,
  EyeOff,
  Hand,
  House,
  Info,
  LayoutGrid,
  List,
  type LucideProps,
  Moon,
  Music,
  Smartphone,
  Sun,
  Pencil,
  Play,
  Plus,
  Repeat,
  Save,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  Square,
  Timer,
  Trash2,
  User,
  Users,
  Video,
  Volume2,
} from 'lucide-react-native';

/**
 * Ponto único de ícones (Lucide — traço moderno). Mapeia nomes semânticos (os antigos do
 * Ionicons, pra não reescrever cada tela) → ícones do Lucide. Trocar de biblioteca no
 * futuro = mexer só aqui.
 */
const MAPA = {
  add: Plus,
  'add-circle-outline': CirclePlus,
  alarm: AlarmClock,
  'arrow-back': ArrowLeft,
  'bookmark-outline': Bookmark,
  calendar: Calendar,
  'calendar-outline': Calendar,
  camera: Camera,
  checkmark: Check,
  'checkmark-circle': CircleCheckBig,
  'checkmark-done-outline': CheckCheck,
  'chevron-back': ChevronLeft,
  'chevron-forward': ChevronRight,
  'close-circle': CircleX,
  'cloud-download-outline': CloudDownload,
  'cloud-offline-outline': CloudOff,
  'cloud-upload-outline': CloudUpload,
  'create-outline': Pencil,
  'ellipsis-vertical': EllipsisVertical,
  'eye-outline': Eye,
  'eye-off-outline': EyeOff,
  grid: LayoutGrid,
  'grid-outline': LayoutGrid,
  'hand-left-outline': Hand,
  'help-circle-outline': CircleHelp,
  home: House,
  'information-circle-outline': Info,
  'list-outline': List,
  'musical-note-outline': Music,
  'musical-notes': Music,
  'musical-notes-outline': Music,
  notifications: Bell,
  'notifications-outline': Bell,
  'people-outline': Users,
  person: User,
  'person-outline': User,
  play: Play,
  'pulse-outline': Activity,
  'repeat-outline': Repeat,
  'save-outline': Save,
  'settings-outline': Settings,
  'share-social-outline': Share2,
  'shield-checkmark-outline': ShieldCheck,
  'shield-outline': Shield,
  'stats-chart-outline': ChartColumn,
  stop: Square,
  'swap-horizontal': ArrowLeftRight,
  'time-outline': Clock,
  'timer-outline': Timer,
  'trash-outline': Trash2,
  'videocam-outline': Video,
  'volume-medium': Volume2,
  'globe-outline': Globe,
  'mic-outline': Mic,
  'mic-off-outline': MicOff,
  'mic-vocal-outline': MicVocal,
  'guitar-outline': Guitar,
  'piano-outline': Piano,
  'drum-outline': Drum,
  'music-outline-2': Music2,
  'music-outline-4': Music4,
  'alert-circle-outline': CircleAlert,
  'business-outline': Building2,
  'mail-outline': Mail,
  'lock-closed-outline': Lock,
  'call-outline': Phone,
  'key-outline': Key,
  'speedometer-outline': Gauge,
  'logo-youtube': SquarePlay,
  'text-outline': Type,
  'search-outline': Search,
  'sunny-outline': Sun,
  'moon-outline': Moon,
  'phone-portrait-outline': Smartphone,
} as const;

export type IconName = keyof typeof MAPA;

export function Icon({ name, size = 22, ...props }: { name: IconName; size?: number } & Omit<LucideProps, 'size'>) {
  const Componente = MAPA[name];
  return <Componente size={size} {...props} />;
}
